### ISSUE TITLE
Unable to git clone SSH to repo in docker.

### ISSUE THREAD

**Issue by superloopnetwork** [bitnami/bitnami-docker-phabricator#147]
Hi there,

I'm most likely doing this wrong. Hence it's not working.... I'm having issues trying to perform a git clone to local SSH repo...

Here is my setup. I have a development server (10.50.30.4) running a VM where Phabricator is installed via docker.

VM has an address of 10.50.30.4 and this is how I access Phabricator via https://10.50.30.4

I'm successful in importing a repo from my external github.com. I can see the repo in Phabricator. In my URI, I see both the github and local:
![image](https://user-images.githubusercontent.com/23246145/83342142-9c1cbd00-a2b9-11ea-80c4-7cff6a902ce3.png)

I've added my SSH public keys (Settings > SSH Public Keys) from the development server (which also have the same IP: 10.50.30.4 as the docker that Phabricator is installed) that I'm trying to "git clone" the repo from by copying the ~/.ssh/id_rsa.pub file.

I'm a bit confused that the VM and the docker of Phabricator has the same IP. How does it differentiate the two if I try and "ssh" to it? via port? I have left everything as default so I assume when I try and do a 'git clone ssh://git@10.50.30.4/diffusion/1/superloop.git' on my development server (10.50.30.4), it's trying to just ssh to itself and not the docker...

Another question I have is, the user 'git'... Do I have to create that so that it allows the SSH to pass through?

This is bugging me as I can't get a simple clone to work due to my lack of understanding. Someone please help.

Thanks.

**Comment by superloopnetwork** [comment]
Apologies... I was able to locate additional guides: https://secure.phabricator.com/book/phabricator/article/diffusion_hosting/

Will have a read and try....

**Comment by superloopnetwork** [comment]
I did everything in the steps but when I try testing, I get this:

root@devvm:~/phabricator# ssh -T -p 2222 git@10.50.30.4
ssh: connect to host 10.50.30.4 port 2222: Connection refused

The problem is, I don't know if it's trying to connect to itself still on port 2222 or the docker container where Phabricator is running...

**Comment by jotamartos** [comment]
Hi @superloopnetwork ,

>I'm a bit confused that the VM and the docker of Phabricator has the same IP. How does it differentiate the two if I try and "ssh" to it? via port?

You can access Phabricator using the private IP of the machine because you configured docker (or docker-compose) to redirect the requests to one specific VM's port to a container's port. If you take a look at the ports configuration of [our docker-compose.yml file](https://github.com/bitnami/bitnami-docker-phabricator/blob/master/docker-compose.yml), you can see that it's redirecting all the request to the VM's ports 80 and 443 to the container's ports 80 and 443.

>root@devvm:~/phabricator# ssh -T -p 2222 git@10.50.30.4
>ssh: connect to host 10.50.30.4 port 2222: Connection refused

That error means that there is not anything running on that port. As I mentioned above, you need to configure the container to receive these requests properly. In this case (and as the port 22 of the dev machine is already in use by the VM itself), you will need to redirect the requests to the 2222 port to the container's port 22. Once you do that, you will be able to connect to the container using ssh. 

I hope that helps.

**Comment by superloopnetwork** [comment]
Fixed... Thanks!
