### ISSUE TITLE
install mercurial by default

### ISSUE THREAD

**Issue by jpedrick** [bitnami/bitnami-docker-phabricator#157]
**Description**
Currently mercurial is not installed by default, so mercurial repositories won't work in this docker image. Seems like this should be installed by default.

add "install_packages mercurial" to Dockerfile

**Comment by carrodher** [comment]
Thanks for the suggestion, we already evaluated the addition of `subversion` and `mercurial` to the Docker image, but in the end, we decided to only bundle `git` as part of the image because is the most used one and the document how users can extend the image in order to add other packages like `subversion` or `mercurial`, on this way the size of the image is not increased and it covers all the use cases. [Here](https://github.com/bitnami/bitnami-docker-phabricator#extend-this-image) you can find instructions about how to extend and customize this image.

**Comment by jpedrick** [comment]
Yes, I'm already installing mercurial on my own. It does result in a small size increase, 1.03GB -> 1.11GB.

Perhaps there can be an official full feature image, git, mercurial, svn, and ssh?

**Comment by miguelaeh** [comment]
Hi @jpedrick ,

> Perhaps there can be an official full feature image, git, mercurial, svn, and ssh?

I am afraid we don't have an image with those requirements. You can always clone this repo and extend the image with your required features.
