### ISSUE TITLE
Git Repository Hosting w/ SSH

### ISSUE THREAD

**Issue by kyledayton** [bitnami/bitnami-docker-phabricator#55]
Is this container configured to provide repository hosting via SSH? I have tried modifying the port forwarding configuration to map 2222 -> 22/tcp, and have even edited the Dockerfile to expose port 22, and manually built the container, but I can't seem to be able to clone any repos (connection refused). Is there something I'm missing?

**Comment by azurewraith** [comment]
I noticed that the `ssh` client binary was missing (in 2017.07-r0) and things didn't work until I manually did the following steps...
`apt-get update`
`apt-get install openssh-client`
`mkdir /home/phabricator`
`mkdir /home/phabricator/.ssh`

so I'd imagine if the openssh-client was not installed, an ssh server is not either...

**Comment by dbarranco** [comment]
Hi @kyledayton we are actually working on update the README with the instructions to add the git repository hosting in phabricator.

I will update this thread when we update our README.

Best regards.

**Comment by dbarranco** [comment]
Hi @kyledayton 

I've been checking the phabricator guide and it's not as simple as installing the sshd server and configuring it. You should persist the sshd server in order to have it each time you make a `docker-compose down` - `docker-compose up`. 

The best approach here would be to add another container with the sshd server on it. This is something we are not going to do **yet**, so, in the meantime you can use the **HTTP repository hosting** (we are working on the README) or follow this guide and have an external repository:
https://docs.bitnami.com/google/apps/phabricator/#how-to-configure-an-external-repository-in-phabricator

**Comment by sameersbn** [comment]
@azurewraith please note the ssh client has been added in [2017.15-r1](https://github.com/bitnami/bitnami-docker-phabricator/releases/tag/2017.15-r1).
