### ISSUE TITLE
Build 2017.32.0-r1 version info claims Phabricator is from April 3 2017

### ISSUE THREAD

**Issue by clockworksoul** [bitnami/bitnami-docker-phabricator#75]
Hi folks. Looking at Phabricator's repo, it would seem that there have been a number of major changes in the past few months. However, it doesn't seem that those changes have made it into the image.

Specifically, version page indicates a Phabricator version from about 4 months ago:

```
phabricator 2460755603cb0ad85c2ab2c2185638a85fcdcc4a (Apr 3 2017)
arcanist 4e2363d8b26d2bd8ca169c40603b4fb582dab72f (Sat, Aug 5) (branched from 5eda40337bb4135ca4929617602686302edc7cc0 on origin)
phutil ee5ebf668ad4fd4c0bae3fbbe6616a5826020aa9 (Fri, Aug 11) (branched from 276f6d304b69767d48f88f65484ce310ee2cf3af on origin)
```

**Steps to reproduce the issue:**

1. Deploy `bitnami/phabricator:2017.32.0-r1` (latest as of this writing)
2. Browse to `/config/version/`
3. Look at the indicated versions.

**Describe the results you received:**

A Phabricator version from Apr 3 2017.

**Describe the results you expected:**

A Phabricator version from Aug 16 2017.

**Comment by jotamartos** [comment]
Hi @clockworksoul,

I've just tried to reproduce the issue but the Phabricator version is the correct one. Please see the following information.

```
root@7f36008f9452:/opt/bitnami/phabricator# git log | head -n 20
commit 5494df72282b1a1240fcbbb145eaf15a22790aae
Merge: 41e823796 45b0fd8f9
Author: epriestley <git@epriestley.com>
Date:   Fri Aug 11 06:21:06 2017 -0700

    (stable) Promote 2017 Week 32

commit 45b0fd8f9b53c5a3712bc0ffc8f78eb416c1e70d
Author: Alex Vandiver <alexmv@dropbox.com>
Date:   Fri Aug 11 05:50:43 2017 -0700

    Remove a debugging "echo" that crept in in dccd799b

    Summary: This echo was accidentally added in dccd799b

    Test Plan: Inspection.

    Reviewers: #blessed_reviewers, epriestley

    Reviewed By: #blessed_reviewers, epriestley
```

![screen shot 2017-08-21 at 11 55 00](https://user-images.githubusercontent.com/8791635/29514157-d1c2fd14-8667-11e7-9aa3-9eead30a0a84.png)

In order to debug it, did you launch any previous version of Phabricator? Please note that we persist some directories when launching the containers. 

In case you want to have a fresh deployment of Phabricator you can run the following command:

```
docker-compose down -v && docker-compose pull && docker-compose up --build --force-recreate
```

Please note that this will remove all the persisted volumes and will recreate the image.

I hope this helps.
Jota

**Comment by clockworksoul** [comment]
Ah, it does!

I have `/opt/bitnami/phabricator` volumed over. That solves that issue. Thank you!

**Comment by sameersbn** [comment]
p.s the above issue reference is incorrect. commit intended to reference issue 76
