### ISSUE TITLE
The init script is not picking up MARIADB_USERNAME correctly

### ISSUE THREAD

**Issue by phpdave11** [bitnami/bitnami-docker-phabricator#96]
I am getting "mysql-c ERROR [canConnect] Connection with 'bn_phabricator' user is unsuccessful" when trying to run the binami phabricator container.

I am specifying the following environment variables when running the container:

MARIADB_HOST=mysql.local
MARIADB_USER=myusername
MARIADB_PASSWORD=mypassword

However it seems to be using 'bn_phabricator' as the user, instead of what I supplied:

```
Welcome to the Bitnami phabricator container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
phabric INFO  Phabricator has being initialized already, restoring...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mysql.local:3306
mysql-c ERROR [canConnect] Connection with 'bn_phabricator' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_phabricator' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_phabricator' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'bn_phabricator' user is unsuccessful
```

**Comment by juan131** [comment]
Hi @phpdave11 

Please note that you're indicating the password for the "root" of the database. However it uses a different user to configure the connection with the database from Phabricator.

The creation of that user (bn_phabricator) is done during the initialisation of the MariaDB container. However, it seems you're using an already existing database instead of creating a new one using the Bitnami MariaDB docker image. 

I am afraid that this image does not support this feature (using custom databases) as you can find on this issue: https://github.com/bitnami/bitnami-docker-phabricator/issues/87
